# Generated by Django 4.1.7 on 2023-02-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
